### ISSUE TITLE
CR: Make a build script that produces a WAR file

### ISSUE THREAD

**Issue by 57Bravo** [opensensorhub/osh-core#20]
As a developer, I'd like to see a build script that rolls osh-core into a WAR file so that I can deploy it on a glassfish, tomcat, or proper jetty application server.

**Comment by sensiasoft** [comment]
For now, OpenSensorHub (OSH) cannot be deployed in just any application server. It only works with Embedded Jetty because it needs to instantiate its own servlets dynamically. It is the OSH application that actually instantiates and control the embedded Jetty HTTP server, not the over way around. And in fact OSH can be used without any web server at all.

Providing a version that can be deployed in an external application server is something that we may address in the future, but not in the short term.
