### ISSUE TITLE
Admin UI: Cannot add AXIS IP Video Camera Sensor to sensor list

### ISSUE THREAD

**Issue by ch08532** [opensensorhub/osh-core#48]
Generated the sensorhub-driver-axis-1.0.0.jar and moved it into the libs folder in order to be discovered by osh.  I am able to see the option in the list but when selected and OK is pressed, the sensor does not appear in the Sensors list.  No errors are thrown on the server.

**Comment by alexrobin** [comment]
This happens because this module depends on two other modules that are shared by all video camera drivers `sensorhub-driver-rtpcam` and `sensorhub-driver-videocam` so these will have to be built and copied to the libs folder as well.

Agreed that we need to make sure proper error messages are generated in this case, so I'm not closing this. In the mean time, I added this info in the module documentation.
